language: cpp
dist: focal
compiler: gcc
os: linux
sudo: true
env:
    - BUILD_TYPE=Debug
addons:
       apt:
             sources:
                 - sourceline: “ppa:ubuntu-toolchain-r/test”
             packages:
                 - gcc-10
                 - g++-10
install:
  
- if [ "$CXX" = "g++" ]; then export CXX="g++-10" CC="gcc-10"; fi
script: 
  - ./build.sh
